title: GoHome
description: 专注于Go语言技术分享，提供实用的编程技巧和最佳实践
baseurl: "/go-home"
url: "https://mari0w.github.io"
show_downloads: false
show_github: false
google_analytics:
theme: jekyll-theme-hacker
author: Mari0w

# 启用语法高亮
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false

collections:
  categories:
    output: true